### ISSUE TITLE
[ci] Fix fuzzing github action

### ISSUE THREAD

**Issue by exdx** [mrgnlabs/marginfi-v2#181]
The fuzzing CI action broke some time ago and currently the CI runs consistently fail. Not related to the actual fuzzing itself. 

```
error[E0635]: unknown feature `stdsimd`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.6/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
```

A/C:
Ensure fuzzing action is running successfully

**Comment by cavemanloverboy** [comment]
this build error is fixed in #185
