### ISSUE TITLE
URGENT. No available collateral error won't let me withdraw even with 31% health

### ISSUE THREAD

**Issue by federicosan** [mrgnlabs/marginfi-v2#209]
I have a position with 33 health or so, it won't let me withdraw any token it even says that there is no available collateral, the collateral is there and it shows on step and on the app, but it will say this when going to the withdraw screen.

My supply collateral is more than 3 times the debt and it won't let me restrusture my collateral in any way it says there is no free collateral to withdraw I need to restructure the debt by selling some positions to other positions but it won't let me.

I know this is a bug because it happens on every pool it even happen on isolated pools with no debt.

**Comment by k0beLeenders** [comment]
@federicosan could you share your address with me so I can simulate? (if you don't feel confortable sharing it here you can open a discord ticket)
